### PR TITLE
cosmetic internal comments

### PR DESCRIPTION
**Pull request by satya-dillikar**
*Issue #, if available:*

*Description of changes:*

User Feedback (internal comments) taken care:

1. Rename 'TAP' To 'VMware' in user-visible resource names.
2. Update the helper text for Username to use 'Tanzu' instead of a 'Pivotal' link 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by satya-dillikar** [comment]
The diff is just cosmetic.
@tlindsay42, please check if the qs linter is broken.

I tried to run it manually on my terminal and got the same error.

```
cfn-lint aws-tap-entrypoint-existing-vpc.template.yaml -a ~/vmw_code/vmw-tanzu-tap/qs-cfn-lint-rules/qs_cfn_lint_rules
E0002 Unknown exception while processing rule W9006: __init__() got an unexpected keyword argument 'encoding'
aws-tap-entrypoint-existing-vpc.template.yaml:1:1
```

**Comment by tlindsay42** [comment]
e2e failed likely due to https://github.com/aws-ia/taskcat/pull/759. Researching...

**Review by tlindsay42 — APPROVED** [review]
